name: sisal_app
description: "GreenArena: Sports Sections Quiz - Learn across sports sections, answer fast, review smarter — fully offline."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  
  # Fonts
  google_fonts: ^6.2.1
  
  # Navigation
  go_router: ^14.6.2
  
  # Charts (optional for future stats)
  fl_chart: ^0.69.2
  
  # Flagsmith integration
  flagsmith: ^3.0.0
  
  # Connectivity and HTTP
  connectivity_plus: ^6.0.5
  http: ^1.2.1
  
  # WebView
  webview_flutter: ^4.7.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/sisal.png